# Generated by Django 5.0.6 on 2025-02-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_userprofile_address_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gst_no',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
