# Generated by Django 5.0.6 on 2025-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_userprofile_gst_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gst_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
