# Generated by Django 5.0.6 on 2025-02-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_alter_userprofile_gst_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gst_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
