# Generated by Django 5.1.6 on 2025-03-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
