# Generated by Django 5.1.6 on 2025-03-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0009_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
    ]
