# Generated by Django 5.1.6 on 2025-03-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0011_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='UserProfile',
        ),
    ]
