# Generated by Django 5.1.6 on 2025-03-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0012_rename_user_order_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='UserProfile',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
