# Generated by Django 5.1.6 on 2025-03-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0015_quotation_quotationitem_delete_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
