# Generated by Django 5.1.6 on 2025-03-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0017_quotation_quotationitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='price',
            new_name='admin_price',
        ),
    ]
