# Generated by Django 5.1.6 on 2025-03-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0019_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
