# Generated by Django 5.1.6 on 2025-03-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0020_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
