# Generated by Django 5.1.6 on 2025-03-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0021_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='admin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
