# Generated by Django 5.1.6 on 2025-03-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0022_quotationitem_price_alter_quotationitem_admin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='admin_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
