# Generated by Django 5.1.6 on 2025-03-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0023_quotationitem_admin_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='payment_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='tracking_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
