# Generated by Django 5.1.6 on 2025-03-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0024_quotationitem_payment_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='tracking_link',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
