# Generated by Django 5.1.6 on 2025-03-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0025_remove_quotationitem_payment_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
