# Generated by Django 5.1.6 on 2025-03-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0026_quotation_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], default='Ordered', max_length=20),
        ),
    ]
