# Generated by Django 5.1.6 on 2025-03-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0027_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
