# Generated by Django 5.0.6 on 2025-02-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_img_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_nogst',
            field=models.IntegerField(blank=True, help_text='Enter the price without GST', null=True),
        ),
    ]
