# Generated by Django 5.1.6 on 2025-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_price_nogst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_nogst',
            field=models.IntegerField(help_text='Enter the price without GST', null=True),
        ),
    ]
