# Generated by Django 5.1.6 on 2025-03-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_price_alter_product_price_nogst'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quaquotation_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_nogst',
            field=models.IntegerField(blank=True, help_text='Enter the price without GST', null=True),
        ),
    ]
