# Generated by Django 5.1.6 on 2025-03-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_quaquotation_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quaquotation_product',
            new_name='quotation_product',
        ),
    ]
